// <auto-generated />
using System;
using DMA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920135534_AddCharacterExtras")]
    partial class AddCharacterExtras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DMA.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DMA.Domain.Entities.CharacterAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("CharacterAttachments");
                });

            modelBuilder.Entity("DMA.Domain.Entities.CharacterFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("CharacterFeatures");
                });

            modelBuilder.Entity("DMA.Domain.Entities.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTurnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("SessionId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("DMA.Domain.Entities.EncounterParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EncounterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterParticipants");
                });

            modelBuilder.Entity("DMA.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("DMA.Domain.Entities.PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortraitPath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("DMA.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterNotes")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlayedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DMA.Domain.Entities.StatBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChallengeRating")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StatBlocks");
                });

            modelBuilder.Entity("DMA.Domain.Entities.CharacterAttachment", b =>
                {
                    b.HasOne("DMA.Domain.Entities.PlayerCharacter", "PlayerCharacter")
                        .WithMany("Attachments")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("DMA.Domain.Entities.CharacterFeature", b =>
                {
                    b.HasOne("DMA.Domain.Entities.PlayerCharacter", "PlayerCharacter")
                        .WithMany("Features")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("DMA.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("DMA.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Encounters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMA.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DMA.Domain.Entities.EncounterParticipant", b =>
                {
                    b.HasOne("DMA.Domain.Entities.Encounter", "Encounter")
                        .WithMany("Participants")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("DMA.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("DMA.Domain.Entities.PlayerCharacter", "PlayerCharacter")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("DMA.Domain.Entities.PlayerCharacter", b =>
                {
                    b.HasOne("DMA.Domain.Entities.Campaign", "Campaign")
                        .WithMany("PlayerCharacters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DMA.Domain.Entities.Currency", "Currency", b1 =>
                        {
                            b1.Property<int>("PlayerCharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CopperPieces")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CopperPieces");

                            b1.Property<int>("ElectrumPieces")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ElectrumPieces");

                            b1.Property<int>("GoldPieces")
                                .HasColumnType("INTEGER")
                                .HasColumnName("GoldPieces");

                            b1.Property<int>("PlatinumPieces")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PlatinumPieces");

                            b1.Property<int>("SilverPieces")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SilverPieces");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.OwnsOne("DMA.Domain.Entities.AbilityScores", "Abilities", b1 =>
                        {
                            b1.Property<int>("PlayerCharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Charisma")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Cha");

                            b1.Property<int>("Constitution")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Con");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Dex");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Int");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Str");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Wis");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.Navigation("Abilities")
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Currency")
                        .IsRequired();
                });

            modelBuilder.Entity("DMA.Domain.Entities.Session", b =>
                {
                    b.HasOne("DMA.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DMA.Domain.Entities.StatBlock", b =>
                {
                    b.OwnsOne("DMA.Domain.Entities.AbilityScores", "Abilities", b1 =>
                        {
                            b1.Property<int>("StatBlockId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Charisma")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Cha");

                            b1.Property<int>("Constitution")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Con");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Dex");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Int");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Str");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Wis");

                            b1.HasKey("StatBlockId");

                            b1.ToTable("StatBlocks");

                            b1.WithOwner()
                                .HasForeignKey("StatBlockId");
                        });

                    b.Navigation("Abilities")
                        .IsRequired();
                });

            modelBuilder.Entity("DMA.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("PlayerCharacters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DMA.Domain.Entities.Encounter", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("DMA.Domain.Entities.PlayerCharacter", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Features");

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
